spring:
  datasource:
    url: ${SMARTLOGIX_SHIPMENT_DB_URL:jdbc:postgresql://localhost:5433/smartlogix_shipment}
    username: ${SMARTLOGIX_SHIPMENT_DB_USERNAME:smartlogix_shipment}
    password: ${SMARTLOGIX_DB_SHIPMENT_PASSWORD}
