package com.smartlogix.inventory.domain;

public enum ActionType {
    CREATE_PRODUCT,
    UPDATE_STOCK,
    ORDER_CREATED,
    ORDER_CANCELLED,
    DELETE_PRODUCT,
    MANUAL_ENTRY,
    MANUAL_EXIT,
    MANUAL_ADJUSTMENT,
    PURCHASE_RECEIPT,
    CUSTOMER_RETURN,
    TRANSFER_OUT,
    TRANSFER_IN
}
