CREATE TABLE inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(60) NOT NULL,
    product_name VARCHAR(120) NOT NULL,
    image_url TEXT,
    category VARCHAR(80),
    brand VARCHAR(80),
    short_description VARCHAR(280),
    sale_price NUMERIC(14, 2) NOT NULL,
    original_price NUMERIC(14, 2),
    featured BOOLEAN NOT NULL,
    fast_shipping BOOLEAN NOT NULL,
    free_shipping BOOLEAN NOT NULL,
    store_pickup BOOLEAN NOT NULL,
    warehouse_code VARCHAR(40) NOT NULL,
    location_zone VARCHAR(20),
    location_aisle VARCHAR(20),
    location_rack INTEGER NOT NULL,
    location_level INTEGER NOT NULL,
    location_position INTEGER NOT NULL,
    available_quantity INTEGER NOT NULL,
    reserved_quantity INTEGER NOT NULL,
    reorder_level INTEGER NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_inventory_items_sku UNIQUE (sku)
);

CREATE TABLE inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id BIGINT,
    product_name VARCHAR(120) NOT NULL,
    sku VARCHAR(60),
    movement_type VARCHAR(30) NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    quantity INTEGER NOT NULL,
    previous_stock INTEGER NOT NULL,
    new_stock INTEGER NOT NULL,
    username VARCHAR(100),
    reason VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE inventory_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(50) NOT NULL,
    sku VARCHAR(60),
    product_name VARCHAR(120),
    username VARCHAR(100) NOT NULL,
    role VARCHAR(60) NOT NULL,
    ip_address VARCHAR(80),
    detail VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE inventory_history_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    product_filter VARCHAR(120),
    movement_type_filter VARCHAR(30),
    action_filter VARCHAR(50),
    user_filter VARCHAR(100),
    start_date DATE,
    end_date DATE,
    min_quantity INTEGER,
    max_quantity INTEGER,
    total_movements BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE product_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(60) NOT NULL,
    username VARCHAR(50) NOT NULL,
    rating INTEGER NOT NULL,
    title VARCHAR(100) NOT NULL,
    comment VARCHAR(1200) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_product_reviews_sku_username UNIQUE (sku, username)
);

CREATE TABLE product_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(60) NOT NULL,
    username VARCHAR(50) NOT NULL,
    question VARCHAR(500) NOT NULL,
    answer VARCHAR(1000),
    answered_by VARCHAR(50),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    answered_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE INDEX idx_inventory_movements_sku ON inventory_movements (sku);
CREATE INDEX idx_inventory_movements_type ON inventory_movements (movement_type);
CREATE INDEX idx_inventory_movements_created_at ON inventory_movements (created_at);
CREATE INDEX idx_inventory_audit_logs_created_at ON inventory_audit_logs (created_at);
CREATE INDEX idx_inventory_history_reports_created_at ON inventory_history_reports (created_at);
CREATE INDEX idx_product_questions_sku ON product_questions (sku);
