CREATE TABLE inventory_stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id BIGINT NOT NULL,
    warehouse_code VARCHAR(40) NOT NULL,
    location_zone VARCHAR(20),
    location_aisle VARCHAR(20),
    location_rack INTEGER NOT NULL,
    location_level INTEGER NOT NULL,
    location_position INTEGER NOT NULL,
    available_quantity INTEGER NOT NULL,
    reserved_quantity INTEGER NOT NULL,
    reorder_level INTEGER NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_inventory_stocks_item
        FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_stocks_warehouse
        FOREIGN KEY (warehouse_code) REFERENCES warehouses (code),
    CONSTRAINT uk_inventory_stocks_item_warehouse
        UNIQUE (inventory_item_id, warehouse_code),
    CONSTRAINT ck_inventory_stocks_available_nonnegative CHECK (available_quantity >= 0),
    CONSTRAINT ck_inventory_stocks_reserved_nonnegative CHECK (reserved_quantity >= 0),
    CONSTRAINT ck_inventory_stocks_reorder_nonnegative CHECK (reorder_level >= 0)
);

INSERT INTO inventory_stocks (
    inventory_item_id, warehouse_code, location_zone, location_aisle,
    location_rack, location_level, location_position,
    available_quantity, reserved_quantity, reorder_level, updated_at
)
SELECT
    id, warehouse_code, location_zone, location_aisle,
    location_rack, location_level, location_position,
    available_quantity, reserved_quantity, reorder_level, updated_at
FROM inventory_items;

CREATE INDEX idx_inventory_stocks_item ON inventory_stocks (inventory_item_id);
CREATE INDEX idx_inventory_stocks_warehouse ON inventory_stocks (warehouse_code);

ALTER TABLE inventory_movements ADD COLUMN warehouse_code VARCHAR(40);

UPDATE inventory_movements movement
SET warehouse_code = item.warehouse_code
FROM inventory_items item
WHERE movement.inventory_item_id = item.id;

CREATE INDEX idx_inventory_movements_warehouse ON inventory_movements (warehouse_code);
