CREATE TABLE suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    business_name VARCHAR(140) NOT NULL,
    tax_id VARCHAR(20) NOT NULL,
    contact_name VARCHAR(120),
    email VARCHAR(160) NOT NULL,
    phone VARCHAR(30),
    address VARCHAR(240),
    payment_terms_days INTEGER NOT NULL,
    lead_time_days INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_suppliers_code UNIQUE (code),
    CONSTRAINT uk_suppliers_tax_id UNIQUE (tax_id),
    CONSTRAINT ck_suppliers_terms CHECK (payment_terms_days >= 0 AND lead_time_days >= 0)
);

CREATE TABLE supplier_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    inventory_item_id BIGINT NOT NULL,
    supplier_sku VARCHAR(60) NOT NULL,
    unit_cost NUMERIC(14, 2) NOT NULL,
    minimum_order_quantity INTEGER NOT NULL,
    preferred BOOLEAN NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_supplier_products_supplier
        FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT fk_supplier_products_item
        FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (id),
    CONSTRAINT uk_supplier_products_supplier_item
        UNIQUE (supplier_id, inventory_item_id),
    CONSTRAINT ck_supplier_products_values
        CHECK (unit_cost > 0 AND minimum_order_quantity > 0)
);

CREATE TABLE purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(40) NOT NULL,
    supplier_id BIGINT NOT NULL,
    warehouse_code VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    expected_at DATE NOT NULL,
    notes VARCHAR(500),
    created_by VARCHAR(100) NOT NULL,
    approved_by VARCHAR(100),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    approved_at TIMESTAMP(6) WITH TIME ZONE,
    received_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_purchase_orders_number UNIQUE (order_number),
    CONSTRAINT fk_purchase_orders_supplier
        FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT fk_purchase_orders_warehouse
        FOREIGN KEY (warehouse_code) REFERENCES warehouses (code),
    CONSTRAINT ck_purchase_orders_status
        CHECK (status IN ('DRAFT', 'APPROVED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED'))
);

CREATE TABLE purchase_order_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    inventory_item_id BIGINT NOT NULL,
    supplier_sku VARCHAR(60) NOT NULL,
    ordered_quantity INTEGER NOT NULL,
    received_quantity INTEGER NOT NULL,
    unit_cost NUMERIC(14, 2) NOT NULL,
    CONSTRAINT fk_purchase_order_lines_order
        FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_purchase_order_lines_item
        FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (id),
    CONSTRAINT uk_purchase_order_lines_order_item
        UNIQUE (purchase_order_id, inventory_item_id),
    CONSTRAINT ck_purchase_order_lines_values
        CHECK (
            ordered_quantity > 0
            AND received_quantity >= 0
            AND received_quantity <= ordered_quantity
            AND unit_cost > 0
        )
);

CREATE INDEX idx_supplier_products_item ON supplier_products (inventory_item_id);
CREATE INDEX idx_purchase_orders_status ON purchase_orders (status);
CREATE INDEX idx_purchase_orders_supplier ON purchase_orders (supplier_id);
CREATE INDEX idx_purchase_orders_created_at ON purchase_orders (created_at);
