CREATE TABLE shipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_code VARCHAR(50) NOT NULL,
    order_number VARCHAR(60) NOT NULL,
    destination_address VARCHAR(255) NOT NULL,
    total_units INTEGER NOT NULL,
    carrier VARCHAR(40) NOT NULL,
    route_code VARCHAR(40) NOT NULL,
    estimated_delivery_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_shipments_tracking_code UNIQUE (tracking_code)
);

CREATE INDEX idx_shipments_order_number ON shipments (order_number);
