CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(50) NOT NULL,
    customer_name VARCHAR(120) NOT NULL,
    customer_email VARCHAR(120) NOT NULL,
    customer_phone VARCHAR(30),
    customer_document VARCHAR(20),
    marketing_opt_in BOOLEAN NOT NULL,
    customer_username VARCHAR(50),
    sales_channel VARCHAR(20) NOT NULL,
    fulfillment_method VARCHAR(20) NOT NULL,
    shipping_address VARCHAR(255),
    shipping_region VARCHAR(80),
    shipping_commune VARCHAR(80),
    billing_address VARCHAR(255),
    delivery_instructions VARCHAR(250),
    pickup_location VARCHAR(120),
    shipping_method VARCHAR(20),
    payment_method VARCHAR(40) NOT NULL,
    payment_status VARCHAR(20) NOT NULL,
    transaction_reference VARCHAR(60),
    payment_authorization_code VARCHAR(30),
    payment_processed_at TIMESTAMP(6) WITH TIME ZONE,
    payment_failure_reason VARCHAR(250),
    refund_reference VARCHAR(60),
    refunded_at TIMESTAMP(6) WITH TIME ZONE,
    refund_amount NUMERIC(14, 2) NOT NULL,
    cancelled_at TIMESTAMP(6) WITH TIME ZONE,
    cancelled_by VARCHAR(80),
    cancellation_reason VARCHAR(250),
    status VARCHAR(30) NOT NULL,
    total_amount NUMERIC(14, 2) NOT NULL,
    tracking_code VARCHAR(40),
    rejection_reason VARCHAR(250),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    subtotal_amount NUMERIC(14, 2),
    discount_amount NUMERIC(14, 2),
    shipping_amount NUMERIC(14, 2) NOT NULL,
    discount_code VARCHAR(255),
    CONSTRAINT uk_orders_order_number UNIQUE (order_number)
);

CREATE TABLE order_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(60) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(14, 2) NOT NULL,
    order_id BIGINT NOT NULL,
    CONSTRAINT fk_order_lines_order
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);

CREATE TABLE discounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    percentage INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    valid_from DATE,
    valid_until DATE,
    only_new_users BOOLEAN,
    assigned_user_id BIGINT,
    used BOOLEAN,
    used_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_discounts_code UNIQUE (code)
);

CREATE INDEX idx_orders_customer_username ON orders (customer_username);
CREATE INDEX idx_orders_created_at ON orders (created_at);
CREATE INDEX idx_order_lines_order ON order_lines (order_id);
