CREATE TABLE cash_register_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_number VARCHAR(50) NOT NULL,
    register_code VARCHAR(40) NOT NULL,
    opened_by VARCHAR(80) NOT NULL,
    closed_by VARCHAR(80),
    status VARCHAR(20) NOT NULL,
    opening_amount NUMERIC(14, 2) NOT NULL,
    cash_sales_amount NUMERIC(14, 2) NOT NULL,
    total_sales_amount NUMERIC(14, 2) NOT NULL,
    sale_count INTEGER NOT NULL,
    expected_cash NUMERIC(14, 2) NOT NULL,
    declared_cash NUMERIC(14, 2),
    cash_difference NUMERIC(14, 2),
    opened_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    closed_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_cash_register_session_number UNIQUE (session_number),
    CONSTRAINT ck_cash_register_opening_amount CHECK (opening_amount >= 0),
    CONSTRAINT ck_cash_register_sale_count CHECK (sale_count >= 0)
);

CREATE UNIQUE INDEX uk_cash_register_open_register
    ON cash_register_sessions (register_code)
    WHERE status = 'OPEN';

CREATE UNIQUE INDEX uk_cash_register_open_user
    ON cash_register_sessions (opened_by)
    WHERE status = 'OPEN';

ALTER TABLE order_lines ADD COLUMN product_name VARCHAR(160);

ALTER TABLE orders ADD COLUMN cash_register_session_id BIGINT;
ALTER TABLE orders ADD COLUMN cashier_username VARCHAR(80);
ALTER TABLE orders ADD COLUMN receipt_number VARCHAR(50);
ALTER TABLE orders ADD COLUMN amount_tendered NUMERIC(14, 2);
ALTER TABLE orders ADD COLUMN change_amount NUMERIC(14, 2) NOT NULL DEFAULT 0;

ALTER TABLE orders ADD CONSTRAINT fk_orders_cash_register_session
    FOREIGN KEY (cash_register_session_id) REFERENCES cash_register_sessions (id);
ALTER TABLE orders ADD CONSTRAINT uk_orders_receipt_number UNIQUE (receipt_number);
ALTER TABLE orders ADD CONSTRAINT ck_orders_amount_tendered
    CHECK (amount_tendered IS NULL OR amount_tendered >= 0);
ALTER TABLE orders ADD CONSTRAINT ck_orders_change_amount CHECK (change_amount >= 0);

CREATE INDEX idx_cash_register_opened_by ON cash_register_sessions (opened_by, opened_at DESC);
CREATE INDEX idx_orders_cash_register_session ON orders (cash_register_session_id, created_at DESC);
