CREATE TABLE post_sale_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_number VARCHAR(50) NOT NULL,
    order_id BIGINT NOT NULL,
    customer_username VARCHAR(50) NOT NULL,
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    preferred_resolution VARCHAR(20) NOT NULL,
    final_resolution VARCHAR(20),
    reason VARCHAR(120) NOT NULL,
    customer_notes VARCHAR(500),
    staff_response VARCHAR(500),
    reviewed_by VARCHAR(80),
    received_by VARCHAR(80),
    resolved_by VARCHAR(80),
    receiving_warehouse_code VARCHAR(40),
    resolution_reference VARCHAR(60),
    replacement_tracking_code VARCHAR(40),
    refund_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
    refund_reference VARCHAR(60),
    requested_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    reviewed_at TIMESTAMP(6) WITH TIME ZONE,
    received_at TIMESTAMP(6) WITH TIME ZONE,
    resolved_at TIMESTAMP(6) WITH TIME ZONE,
    cancelled_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_post_sale_request_number UNIQUE (request_number),
    CONSTRAINT fk_post_sale_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_post_sale_refund_amount CHECK (refund_amount >= 0)
);

CREATE TABLE post_sale_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    sku VARCHAR(60) NOT NULL,
    product_name VARCHAR(160) NOT NULL,
    requested_quantity INTEGER NOT NULL,
    received_quantity INTEGER NOT NULL DEFAULT 0,
    restocked_quantity INTEGER NOT NULL DEFAULT 0,
    unit_price NUMERIC(14, 2) NOT NULL,
    product_condition VARCHAR(20),
    CONSTRAINT fk_post_sale_line_request
        FOREIGN KEY (request_id) REFERENCES post_sale_requests (id) ON DELETE CASCADE,
    CONSTRAINT ck_post_sale_requested_quantity CHECK (requested_quantity > 0),
    CONSTRAINT ck_post_sale_received_quantity CHECK (received_quantity >= 0),
    CONSTRAINT ck_post_sale_restocked_quantity CHECK (restocked_quantity >= 0),
    CONSTRAINT uk_post_sale_request_sku UNIQUE (request_id, sku)
);

CREATE INDEX idx_post_sale_customer ON post_sale_requests (customer_username, requested_at DESC);
CREATE INDEX idx_post_sale_status ON post_sale_requests (status, requested_at DESC);
CREATE INDEX idx_post_sale_order ON post_sale_requests (order_id);
CREATE INDEX idx_post_sale_lines_request ON post_sale_lines (request_id);
