CREATE TABLE order_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_username VARCHAR(50),
    recipient_email VARCHAR(120) NOT NULL,
    order_number VARCHAR(50) NOT NULL,
    type VARCHAR(30) NOT NULL,
    title VARCHAR(160) NOT NULL,
    message VARCHAR(1200) NOT NULL,
    delivery_status VARCHAR(20) NOT NULL,
    failure_reason VARCHAR(300),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    sent_at TIMESTAMP(6) WITH TIME ZONE,
    read_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT ck_notification_delivery_status
        CHECK (delivery_status IN ('PENDING', 'SENT', 'FAILED'))
);

CREATE INDEX idx_notification_customer
    ON order_notifications (customer_username, created_at DESC);
CREATE INDEX idx_notification_delivery
    ON order_notifications (delivery_status, created_at DESC);
CREATE INDEX idx_notification_order
    ON order_notifications (order_number, created_at DESC);
